name: CI

on:
  workflow_dispatch:

env:
  SERVICE_ACCOUNT: sa-iac-sot@prj-iac-sot.iam.gserviceaccount.com
  SERVICE_ACCOUNT_PLAN: sa-iac-sot@prj-iac-sot.iam.gserviceaccount.com
  WIF_PROVIDER: projects/955699112680/locations/global/workloadIdentityPools/wif-sot-pool-iac/providers/wif-sot-prvd-iac-github-public
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock
  TF_VERSION: 1.12.2

jobs:
  build:
    permissions:
      contents: read
      id-token: write
      pull-requests: write

    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - id: gcp-auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{env.WIF_PROVIDER}}
          service_account: ${{env.service_account}}
          access_token_lifetime: 900s.
