name: "Sample"

on:
  workflow_dispatch:
    inputs: {}

jobs:
  pr:
    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
      - id: checkout
        name: Checkout repository
        run: echo "test"
